import { randomUUID } from "crypto";
import path from "path";
import { listTasks } from "@/lib/tasks-store";
import { loadStore, saveStore } from "@/lib/mongo-store";

export type ScheduleCategory = "class" | "study" | "exam" | "event";

export type ScheduleBlockRecord = {
  id: string;
  userId: string;
  title: string;
  subject: string;
  category: ScheduleCategory;
  dayOfWeek: number;
  startTime: string;
  endTime: string;
  location: string;
  autoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
};

type SchedulerStore = {
  blocks: ScheduleBlockRecord[];
};

const dataDir = path.join(process.cwd(), "data");
const schedulerFile = path.join(dataDir, "scheduler.json");

const dayLabels = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

function nowIso() {
  return new Date().toISOString();
}

function userHash(userId: string) {
  return userId.split("").reduce((sum, char) => sum + char.charCodeAt(0), 0);
}

function parseTimeToMinutes(time: string) {
  const match = time.match(/^(\d{2}):(\d{2})$/);
  if (!match) {
    return null;
  }

  const hours = Number(match[1]);
  const minutes = Number(match[2]);

  if (!Number.isInteger(hours) || !Number.isInteger(minutes)) {
    return null;
  }

  if (hours < 0 || hours > 23 || minutes < 0 || minutes > 59) {
    return null;
  }

  return hours * 60 + minutes;
}

function minutesToTime(totalMinutes: number) {
  const hours = Math.floor(totalMinutes / 60)
    .toString()
    .padStart(2, "0");
  const minutes = (totalMinutes % 60).toString().padStart(2, "0");
  return `${hours}:${minutes}`;
}

function clampDayOfWeek(dayOfWeek: number) {
  if (dayOfWeek < 0) {
    return 0;
  }

  if (dayOfWeek > 6) {
    return 6;
  }

  return Math.floor(dayOfWeek);
}

function getWeekdayFromDateString(value: string) {
  const parsed = Date.parse(value);
  if (Number.isNaN(parsed)) {
    return null;
  }

  return new Date(parsed).getDay();
}

async function readStore(): Promise<SchedulerStore> {
  return loadStore<SchedulerStore>({
    collectionName: "scheduler",
    legacyFilePath: schedulerFile,
    initialValue: { blocks: [] },
  });
}

async function writeStore(store: SchedulerStore) {
  await saveStore({
    collectionName: "scheduler",
    legacyFilePath: schedulerFile,
    value: store,
  });
}

async function ensureSeedDataForUser(userId: string): Promise<SchedulerStore> {
  const store = await readStore();
  const hasBlocks = store.blocks.some((block) => block.userId === userId);

  if (hasBlocks) {
    return store;
  }

  const hash = userHash(userId);
  const seed: Array<Omit<ScheduleBlockRecord, "id" | "userId" | "createdAt" | "updatedAt">> = [
    {
      title: "Operating Systems Lecture",
      subject: "Operating Systems",
      category: "class",
      dayOfWeek: 1,
      startTime: "09:00",
      endTime: "10:30",
      location: "Block A - 302",
      autoGenerated: false,
    },
    {
      title: "DBMS Lab",
      subject: "DBMS",
      category: "class",
      dayOfWeek: 2,
      startTime: "14:00",
      endTime: "16:00",
      location: "Lab 4",
      autoGenerated: false,
    },
    {
      title: "Mock Interview",
      subject: "Placement",
      category: "event",
      dayOfWeek: 4,
      startTime: "17:00",
      endTime: "18:00",
      location: "Career Cell",
      autoGenerated: false,
    },
    {
      title: "Campus Quiz Prep",
      subject: "Aptitude",
      category: "exam",
      dayOfWeek: (hash % 3) + 3,
      startTime: "19:00",
      endTime: "20:00",
      location: "Library",
      autoGenerated: false,
    },
  ];

  const now = nowIso();

  for (const item of seed) {
    store.blocks.push({
      ...item,
      id: randomUUID(),
      userId,
      createdAt: now,
      updatedAt: now,
    });
  }

  await writeStore(store);
  return store;
}

function sortBlocks(blocks: ScheduleBlockRecord[]) {
  return [...blocks].sort((a, b) => {
    if (a.dayOfWeek !== b.dayOfWeek) {
      return a.dayOfWeek - b.dayOfWeek;
    }

    return (parseTimeToMinutes(a.startTime) ?? 0) - (parseTimeToMinutes(b.startTime) ?? 0);
  });
}

function getFreeSlotsForUserBlocks(blocks: ScheduleBlockRecord[]) {
  const startMinutes = 8 * 60;
  const endMinutes = 22 * 60;
  const minimumSlot = 45;

  const byDay = Array.from({ length: 7 }).map((_, dayOfWeek) =>
    sortBlocks(blocks.filter((item) => item.dayOfWeek === dayOfWeek)),
  );

  const slots: Array<{
    dayOfWeek: number;
    dayLabel: string;
    startTime: string;
    endTime: string;
    durationMinutes: number;
  }> = [];

  for (let day = 0; day < byDay.length; day += 1) {
    const dayBlocks = byDay[day];
    let cursor = startMinutes;

    for (const block of dayBlocks) {
      const start = parseTimeToMinutes(block.startTime);
      const end = parseTimeToMinutes(block.endTime);

      if (start === null || end === null) {
        continue;
      }

      if (start - cursor >= minimumSlot) {
        slots.push({
          dayOfWeek: day,
          dayLabel: dayLabels[day],
          startTime: minutesToTime(cursor),
          endTime: minutesToTime(start),
          durationMinutes: start - cursor,
        });
      }

      cursor = Math.max(cursor, end);
    }

    if (endMinutes - cursor >= minimumSlot) {
      slots.push({
        dayOfWeek: day,
        dayLabel: dayLabels[day],
        startTime: minutesToTime(cursor),
        endTime: minutesToTime(endMinutes),
        durationMinutes: endMinutes - cursor,
      });
    }
  }

  return slots;
}

function validateTimeRange(startTime: string, endTime: string) {
  const start = parseTimeToMinutes(startTime);
  const end = parseTimeToMinutes(endTime);

  if (start === null || end === null) {
    return false;
  }

  return end > start;
}

function hasOverlap(blocks: ScheduleBlockRecord[], candidate: { dayOfWeek: number; startTime: string; endTime: string }) {
  const start = parseTimeToMinutes(candidate.startTime);
  const end = parseTimeToMinutes(candidate.endTime);

  if (start === null || end === null) {
    return true;
  }

  return blocks.some((block) => {
    if (block.dayOfWeek !== candidate.dayOfWeek) {
      return false;
    }

    const blockStart = parseTimeToMinutes(block.startTime);
    const blockEnd = parseTimeToMinutes(block.endTime);

    if (blockStart === null || blockEnd === null) {
      return false;
    }

    return start < blockEnd && end > blockStart;
  });
}

export async function listSchedule(userId: string) {
  const store = await ensureSeedDataForUser(userId);
  const userBlocks = sortBlocks(store.blocks.filter((item) => item.userId === userId));
  const freeSlots = getFreeSlotsForUserBlocks(userBlocks);

  const totalMinutes = userBlocks.reduce((sum, item) => {
    const start = parseTimeToMinutes(item.startTime) ?? 0;
    const end = parseTimeToMinutes(item.endTime) ?? 0;
    return sum + Math.max(0, end - start);
  }, 0);

  const studyMinutes = userBlocks
    .filter((item) => item.category === "study")
    .reduce((sum, item) => {
      const start = parseTimeToMinutes(item.startTime) ?? 0;
      const end = parseTimeToMinutes(item.endTime) ?? 0;
      return sum + Math.max(0, end - start);
    }, 0);

  return {
    blocks: userBlocks,
    freeSlots,
    dashboard: {
      totalBlocks: userBlocks.length,
      totalHours: Number((totalMinutes / 60).toFixed(1)),
      studyHours: Number((studyMinutes / 60).toFixed(1)),
      freeSlotsCount: freeSlots.length,
    },
    options: {
      categories: ["class", "study", "exam", "event"] as ScheduleCategory[],
      days: dayLabels.map((label, index) => ({ value: index, label })),
    },
  };
}

export async function createScheduleBlock(input: {
  userId: string;
  title: string;
  subject?: string;
  category?: ScheduleCategory;
  dayOfWeek: number;
  startTime: string;
  endTime: string;
  location?: string;
  autoGenerated?: boolean;
}) {
  const store = await ensureSeedDataForUser(input.userId);
  const dayOfWeek = clampDayOfWeek(input.dayOfWeek);
  const category = input.category ?? "study";

  if (!validateTimeRange(input.startTime, input.endTime)) {
    throw new Error("Invalid time range");
  }

  const userBlocks = store.blocks.filter((item) => item.userId === input.userId);
  const overlap = hasOverlap(userBlocks, {
    dayOfWeek,
    startTime: input.startTime,
    endTime: input.endTime,
  });

  if (overlap) {
    throw new Error("Time block overlaps with existing schedule");
  }

  const now = nowIso();
  const block: ScheduleBlockRecord = {
    id: randomUUID(),
    userId: input.userId,
    title: input.title.trim(),
    subject: (input.subject ?? "General").trim() || "General",
    category,
    dayOfWeek,
    startTime: input.startTime,
    endTime: input.endTime,
    location: (input.location ?? "").trim(),
    autoGenerated: Boolean(input.autoGenerated),
    createdAt: now,
    updatedAt: now,
  };

  store.blocks.push(block);
  await writeStore(store);

  return block;
}

export async function autoGenerateStudyPlan(userId: string) {
  const store = await ensureSeedDataForUser(userId);

  store.blocks = store.blocks.filter((item) => !(item.userId === userId && item.category === "study" && item.autoGenerated));

  const currentBlocks = sortBlocks(store.blocks.filter((item) => item.userId === userId));
  const freeSlots = getFreeSlotsForUserBlocks(currentBlocks)
    .filter((slot) => slot.durationMinutes >= 45)
    .sort((a, b) => {
      const dayDiff = a.dayOfWeek - b.dayOfWeek;
      if (dayDiff !== 0) {
        return dayDiff;
      }
      return (parseTimeToMinutes(a.startTime) ?? 0) - (parseTimeToMinutes(b.startTime) ?? 0);
    });

  const taskData = await listTasks(userId);
  const pendingTasks = taskData.tasks.filter((task) => task.status !== "done");

  const tasksByPriority = [...pendingTasks].sort((a, b) => {
    const priorityOrder = { high: 0, medium: 1, low: 2 } as const;
    const left = priorityOrder[a.priority];
    const right = priorityOrder[b.priority];

    if (left !== right) {
      return left - right;
    }

    return Date.parse(a.deadline) - Date.parse(b.deadline);
  });

  const today = new Date().getDay();
  const rotateDayOrder = Array.from({ length: 7 }).map((_, offset) => (today + offset) % 7);

  const sortedSlots = freeSlots.sort((a, b) => {
    const left = rotateDayOrder.indexOf(a.dayOfWeek);
    const right = rotateDayOrder.indexOf(b.dayOfWeek);

    if (left !== right) {
      return left - right;
    }

    return (parseTimeToMinutes(a.startTime) ?? 0) - (parseTimeToMinutes(b.startTime) ?? 0);
  });

  let slotIndex = 0;
  let created = 0;
  const createdBlocks: ScheduleBlockRecord[] = [];

  for (const task of tasksByPriority) {
    if (slotIndex >= sortedSlots.length) {
      break;
    }

    const targetMinutes = Math.max(45, Math.min(120, task.estimatedMinutes));
    let remaining = targetMinutes;

    while (remaining >= 45 && slotIndex < sortedSlots.length) {
      const slot = sortedSlots[slotIndex];
      const slotStart = parseTimeToMinutes(slot.startTime);
      const slotEnd = parseTimeToMinutes(slot.endTime);

      if (slotStart === null || slotEnd === null) {
        slotIndex += 1;
        continue;
      }

      const usable = Math.min(remaining, slot.durationMinutes);
      if (usable < 45) {
        slotIndex += 1;
        continue;
      }

      const blockStart = slotStart;
      const blockEnd = slotStart + usable;

      const block: ScheduleBlockRecord = {
        id: randomUUID(),
        userId,
        title: `Study: ${task.title}`,
        subject: task.course,
        category: "study",
        dayOfWeek: slot.dayOfWeek,
        startTime: minutesToTime(blockStart),
        endTime: minutesToTime(blockEnd),
        location: "Self Study",
        autoGenerated: true,
        createdAt: nowIso(),
        updatedAt: nowIso(),
      };

      store.blocks.push(block);
      createdBlocks.push(block);
      created += 1;

      remaining -= usable;

      if (blockEnd >= slotEnd - 15) {
        slotIndex += 1;
      } else {
        sortedSlots[slotIndex] = {
          ...slot,
          startTime: minutesToTime(blockEnd),
          durationMinutes: slotEnd - blockEnd,
        };
      }
    }
  }

  await writeStore(store);

  return {
    created,
    blocks: sortBlocks(createdBlocks),
  };
}

export async function createStudySessionFromFreeSlot(input: {
  userId: string;
  subject: string;
  dayOfWeek: number;
  startTime: string;
  durationMinutes: number;
}) {
  const start = parseTimeToMinutes(input.startTime);

  if (start === null) {
    throw new Error("Invalid start time");
  }

  const endTime = minutesToTime(start + Math.max(30, input.durationMinutes));

  return createScheduleBlock({
    userId: input.userId,
    title: `${input.subject} Focus Session`,
    subject: input.subject,
    category: "study",
    dayOfWeek: input.dayOfWeek,
    startTime: input.startTime,
    endTime,
    location: "Library",
    autoGenerated: false,
  });
}

export function dayLabelFromIndex(index: number) {
  return dayLabels[clampDayOfWeek(index)];
}

export function categoryFromTaskDate(deadline: string) {
  const day = getWeekdayFromDateString(deadline);
  if (day === null) {
    return null;
  }

  return day;
}
