import { NextResponse } from "next/server";
import { z } from "zod";
import { getCurrentUser } from "@/lib/auth/server";
import {
  autoGenerateStudyPlan,
  createScheduleBlock,
  createStudySessionFromFreeSlot,
  type ScheduleCategory,
  listSchedule,
} from "@/lib/scheduler-store";

const categoryValues = ["class", "study", "exam", "event"] as const;

const createBlockSchema = z.object({
  title: z.string().min(2, "Title is required").max(120),
  subject: z.string().max(80).optional(),
  category: z.enum(categoryValues).optional(),
  dayOfWeek: z.number().int().min(0).max(6),
  startTime: z.string().regex(/^\d{2}:\d{2}$/, "Start time must be HH:MM"),
  endTime: z.string().regex(/^\d{2}:\d{2}$/, "End time must be HH:MM"),
  location: z.string().max(120).optional(),
});

const createSessionSchema = z.object({
  subject: z.string().min(2, "Subject is required").max(80),
  dayOfWeek: z.number().int().min(0).max(6),
  startTime: z.string().regex(/^\d{2}:\d{2}$/, "Start time must be HH:MM"),
  durationMinutes: z.number().int().min(30).max(240),
});

const actionSchema = z.object({
  action: z.enum(["create_block", "auto_generate", "plan_session"]),
  payload: z.unknown().optional(),
});

export async function GET() {
  const user = await getCurrentUser();

  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const scheduler = await listSchedule(user.id);
    return NextResponse.json(scheduler);
  } catch (error) {
    console.error("Scheduler GET API error", error);
    return NextResponse.json({ error: "Could not fetch scheduler" }, { status: 500 });
  }
}

export async function POST(request: Request) {
  const user = await getCurrentUser();

  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const body = await request.json();
    const parsedAction = actionSchema.safeParse(body);

    if (!parsedAction.success) {
      return NextResponse.json({ error: "Invalid action payload" }, { status: 400 });
    }

    if (parsedAction.data.action === "auto_generate") {
      const result = await autoGenerateStudyPlan(user.id);
      return NextResponse.json({
        message: `Generated ${result.created} study session${result.created === 1 ? "" : "s"}.`,
        generated: result,
      });
    }

    if (parsedAction.data.action === "plan_session") {
      const parsedSession = createSessionSchema.safeParse(parsedAction.data.payload);
      if (!parsedSession.success) {
        const [issue] = parsedSession.error.issues;
        return NextResponse.json({ error: issue?.message ?? "Invalid session payload" }, { status: 400 });
      }

      const session = await createStudySessionFromFreeSlot({
        userId: user.id,
        ...parsedSession.data,
      });

      return NextResponse.json({
        message: "Study session planned.",
        session,
      });
    }

    const parsedBlock = createBlockSchema.safeParse(parsedAction.data.payload);
    if (!parsedBlock.success) {
      const [issue] = parsedBlock.error.issues;
      return NextResponse.json({ error: issue?.message ?? "Invalid block payload" }, { status: 400 });
    }

    const block = await createScheduleBlock({
      userId: user.id,
      title: parsedBlock.data.title,
      subject: parsedBlock.data.subject,
      category: parsedBlock.data.category as ScheduleCategory | undefined,
      dayOfWeek: parsedBlock.data.dayOfWeek,
      startTime: parsedBlock.data.startTime,
      endTime: parsedBlock.data.endTime,
      location: parsedBlock.data.location,
      autoGenerated: false,
    });

    return NextResponse.json({
      message: "Schedule block created.",
      block,
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unexpected scheduler error";
    const status = message.toLowerCase().includes("overlap") || message.toLowerCase().includes("invalid") ? 400 : 500;

    console.error("Scheduler POST API error", error);
    return NextResponse.json({ error: message }, { status });
  }
}
