"use client";

import { useEffect, useMemo, useState } from "react";
import {
  AlarmClock,
  CalendarDays,
  Clock3,
  Filter,
  Plus,
  Sparkles,
  WandSparkles,
} from "lucide-react";

type ScheduleCategory = "class" | "study" | "exam" | "event";

type ScheduleBlock = {
  id: string;
  title: string;
  subject: string;
  category: ScheduleCategory;
  dayOfWeek: number;
  startTime: string;
  endTime: string;
  location: string;
  autoGenerated: boolean;
};

type FreeSlot = {
  dayOfWeek: number;
  dayLabel: string;
  startTime: string;
  endTime: string;
  durationMinutes: number;
};

type SchedulerResponse = {
  blocks: ScheduleBlock[];
  freeSlots: FreeSlot[];
  dashboard: {
    totalBlocks: number;
    totalHours: number;
    studyHours: number;
    freeSlotsCount: number;
  };
  options: {
    categories: ScheduleCategory[];
    days: Array<{ value: number; label: string }>;
  };
};

const categoryClassMap: Record<ScheduleCategory, string> = {
  class: "border-sky-400/40 bg-sky-500/10 text-sky-700 dark:text-sky-300",
  study: "border-indigo-400/40 bg-indigo-500/10 text-indigo-700 dark:text-indigo-300",
  exam: "border-rose-400/40 bg-rose-500/10 text-rose-700 dark:text-rose-300",
  event: "border-emerald-400/40 bg-emerald-500/10 text-emerald-700 dark:text-emerald-300",
};

const categoryDotMap: Record<ScheduleCategory, string> = {
  class: "bg-sky-500",
  study: "bg-indigo-500",
  exam: "bg-rose-500",
  event: "bg-emerald-500",
};

const initialForm = {
  title: "",
  subject: "",
  category: "study" as ScheduleCategory,
  dayOfWeek: "1",
  startTime: "10:00",
  endTime: "11:00",
  location: "",
};

function categoryLabel(value: ScheduleCategory) {
  return value.slice(0, 1).toUpperCase() + value.slice(1);
}

function toHours(minutes: number) {
  return `${(minutes / 60).toFixed(1)}h`;
}

export function SchedulerHub() {
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [feedback, setFeedback] = useState<string | null>(null);

  const [showCreateModal, setShowCreateModal] = useState(false);
  const [quickSubject, setQuickSubject] = useState("DSA");

  const [categoryFilter, setCategoryFilter] = useState("");
  const [dayFilter, setDayFilter] = useState("");

  const [form, setForm] = useState(initialForm);

  const [blocks, setBlocks] = useState<ScheduleBlock[]>([]);
  const [freeSlots, setFreeSlots] = useState<FreeSlot[]>([]);
  const [dashboard, setDashboard] = useState<SchedulerResponse["dashboard"] | null>(null);
  const [options, setOptions] = useState<SchedulerResponse["options"]>({
    categories: ["class", "study", "exam", "event"],
    days: [
      { value: 0, label: "Sunday" },
      { value: 1, label: "Monday" },
      { value: 2, label: "Tuesday" },
      { value: 3, label: "Wednesday" },
      { value: 4, label: "Thursday" },
      { value: 5, label: "Friday" },
      { value: 6, label: "Saturday" },
    ],
  });

  const fetchScheduler = async () => {
    setLoading(true);
    setError(null);

    try {
      const response = await fetch("/api/scheduler", { cache: "no-store" });
      const data = (await response.json()) as SchedulerResponse | { error?: string };

      if (!response.ok) {
        throw new Error("error" in data ? data.error ?? "Could not load scheduler" : "Could not load scheduler");
      }

      const schedulerData = data as SchedulerResponse;
      setBlocks(schedulerData.blocks);
      setFreeSlots(schedulerData.freeSlots);
      setDashboard(schedulerData.dashboard);
      setOptions(schedulerData.options);
    } catch (requestError) {
      const message = requestError instanceof Error ? requestError.message : "Could not load scheduler";
      setError(message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    void fetchScheduler();
  }, []);

  const groupedByDay = useMemo(() => {
    const dayMap = new Map<number, ScheduleBlock[]>();

    for (const day of options.days) {
      dayMap.set(day.value, []);
    }

    for (const block of blocks) {
      const categoryMatch = !categoryFilter || block.category === categoryFilter;
      const dayMatch = dayFilter === "" || String(block.dayOfWeek) === dayFilter;

      if (!categoryMatch || !dayMatch) {
        continue;
      }

      const current = dayMap.get(block.dayOfWeek) ?? [];
      current.push(block);
      dayMap.set(block.dayOfWeek, current);
    }

    for (const [day, items] of dayMap.entries()) {
      items.sort((a, b) => a.startTime.localeCompare(b.startTime));
      dayMap.set(day, items);
    }

    return dayMap;
  }, [blocks, options.days, categoryFilter, dayFilter]);

  const filteredSlots = useMemo(() => {
    return freeSlots
      .filter((slot) => (dayFilter === "" ? true : String(slot.dayOfWeek) === dayFilter))
      .slice(0, 10);
  }, [freeSlots, dayFilter]);

  const handleCreateBlock = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    if (saving) {
      return;
    }

    setSaving(true);
    setError(null);
    setFeedback(null);

    try {
      const response = await fetch("/api/scheduler", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          action: "create_block",
          payload: {
            title: form.title,
            subject: form.subject,
            category: form.category,
            dayOfWeek: Number(form.dayOfWeek),
            startTime: form.startTime,
            endTime: form.endTime,
            location: form.location,
          },
        }),
      });

      const data = (await response.json()) as { error?: string; message?: string };

      if (!response.ok) {
        throw new Error(data.error ?? "Could not create block");
      }

      setForm(initialForm);
      setShowCreateModal(false);
      setFeedback(data.message ?? "Schedule block created");
      await fetchScheduler();
    } catch (requestError) {
      const message = requestError instanceof Error ? requestError.message : "Could not create block";
      setError(message);
    } finally {
      setSaving(false);
    }
  };

  const handleAutoGenerate = async () => {
    if (saving) {
      return;
    }

    setSaving(true);
    setError(null);
    setFeedback(null);

    try {
      const response = await fetch("/api/scheduler", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ action: "auto_generate" }),
      });

      const data = (await response.json()) as { error?: string; message?: string };

      if (!response.ok) {
        throw new Error(data.error ?? "Could not auto-generate timetable");
      }

      setFeedback(data.message ?? "Auto-generated study sessions");
      await fetchScheduler();
    } catch (requestError) {
      const message = requestError instanceof Error ? requestError.message : "Could not auto-generate timetable";
      setError(message);
    } finally {
      setSaving(false);
    }
  };

  const handlePlanFromFreeSlot = async (slot: FreeSlot) => {
    if (saving) {
      return;
    }

    setSaving(true);
    setError(null);
    setFeedback(null);

    try {
      const response = await fetch("/api/scheduler", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          action: "plan_session",
          payload: {
            subject: quickSubject,
            dayOfWeek: slot.dayOfWeek,
            startTime: slot.startTime,
            durationMinutes: Math.min(90, Math.max(45, slot.durationMinutes)),
          },
        }),
      });

      const data = (await response.json()) as { error?: string; message?: string };

      if (!response.ok) {
        throw new Error(data.error ?? "Could not plan session");
      }

      setFeedback(data.message ?? "Study session planned");
      await fetchScheduler();
    } catch (requestError) {
      const message = requestError instanceof Error ? requestError.message : "Could not plan session";
      setError(message);
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return (
      <section className="page-enter rounded-3xl border border-[var(--border)] bg-[var(--card)] p-8 shadow-sm">
        <p className="text-sm text-[var(--text-secondary)]">Loading scheduler...</p>
      </section>
    );
  }

  return (
    <section className="page-enter space-y-6">
      <div className="rounded-3xl border border-[var(--border)] bg-[var(--card)] p-6 shadow-sm">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div>
            <div className="mb-2 inline-flex items-center gap-2 rounded-full border border-[var(--border)] bg-[var(--bg-muted)] px-3 py-1 text-xs font-semibold uppercase tracking-[0.12em] text-[var(--text-secondary)]">
              <CalendarDays size={14} />
              Smart Timetable
            </div>
            <h1 className="text-2xl font-semibold tracking-tight text-[var(--text-primary)]">Scheduler & Free Slot Planner</h1>
            <p className="mt-1 text-sm text-[var(--text-secondary)]">
              Auto-generate weekly study plans, detect open time blocks, and build a focused routine.
            </p>
          </div>

          <div className="flex flex-wrap items-center gap-2">
            <button
              type="button"
              onClick={handleAutoGenerate}
              disabled={saving}
              className="inline-flex items-center gap-2 rounded-xl border border-indigo-400/40 bg-indigo-500/15 px-4 py-2 text-sm font-semibold text-indigo-700 transition-all duration-200 hover:-translate-y-0.5 hover:bg-indigo-500/20 disabled:opacity-60 dark:text-indigo-300"
            >
              <WandSparkles size={16} />
              Auto-Generate
            </button>
            <button
              type="button"
              onClick={() => setShowCreateModal(true)}
              className="inline-flex items-center gap-2 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-4 py-2 text-sm font-semibold text-[var(--text-primary)] transition-all duration-200 hover:-translate-y-0.5 hover:shadow"
            >
              <Plus size={16} />
              Add Time Block
            </button>
          </div>
        </div>

        {feedback ? <p className="mt-3 text-sm text-emerald-600 dark:text-emerald-400">{feedback}</p> : null}
        {error ? <p className="mt-3 text-sm text-rose-600 dark:text-rose-400">{error}</p> : null}
      </div>

      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <WidgetCard title="Scheduled Blocks" value={String(dashboard?.totalBlocks ?? 0)} hint="This week" icon={<CalendarDays size={18} />} />
        <WidgetCard title="Planned Hours" value={`${dashboard?.totalHours ?? 0}h`} hint="All categories" icon={<Clock3 size={18} />} />
        <WidgetCard title="Study Hours" value={`${dashboard?.studyHours ?? 0}h`} hint="Focused sessions" icon={<Sparkles size={18} />} />
        <WidgetCard
          title="Open Free Slots"
          value={String(dashboard?.freeSlotsCount ?? 0)}
          hint="Detected windows"
          icon={<AlarmClock size={18} />}
        />
      </div>

      <div className="grid gap-6 xl:grid-cols-[1fr_320px]">
        <div className="space-y-4 rounded-3xl border border-[var(--border)] bg-[var(--card)] p-5 shadow-sm">
          <div className="flex flex-wrap items-center gap-2">
            <div className="inline-flex items-center gap-2 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 py-2 text-xs font-semibold uppercase tracking-[0.12em] text-[var(--text-secondary)]">
              <Filter size={14} />
              Filters
            </div>
            <select
              value={categoryFilter}
              onChange={(event) => setCategoryFilter(event.target.value)}
              className="rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 py-2 text-sm text-[var(--text-primary)] outline-none"
            >
              <option value="">All Categories</option>
              {options.categories.map((category) => (
                <option key={category} value={category}>
                  {categoryLabel(category)}
                </option>
              ))}
            </select>

            <select
              value={dayFilter}
              onChange={(event) => setDayFilter(event.target.value)}
              className="rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 py-2 text-sm text-[var(--text-primary)] outline-none"
            >
              <option value="">All Days</option>
              {options.days.map((day) => (
                <option key={day.value} value={day.value}>
                  {day.label}
                </option>
              ))}
            </select>
          </div>

          <div className="grid gap-4 lg:grid-cols-2 2xl:grid-cols-3">
            {options.days.map((day) => {
              const items = groupedByDay.get(day.value) ?? [];

              return (
                <article
                  key={day.value}
                  className="group rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-4 transition-all duration-300 hover:-translate-y-0.5 hover:shadow"
                >
                  <div className="mb-3 flex items-center justify-between">
                    <h3 className="text-sm font-semibold text-[var(--text-primary)]">{day.label}</h3>
                    <span className="rounded-full border border-[var(--border)] bg-[var(--card)] px-2 py-0.5 text-[10px] font-semibold uppercase tracking-[0.08em] text-[var(--text-secondary)]">
                      {items.length} blocks
                    </span>
                  </div>

                  <div className="space-y-2">
                    {items.length === 0 ? (
                      <p className="rounded-xl border border-dashed border-[var(--border)] px-3 py-2 text-xs text-[var(--text-secondary)]">No blocks</p>
                    ) : (
                      items.map((block) => (
                        <div
                          key={block.id}
                          className={`rounded-xl border px-3 py-2 transition-transform duration-200 group-hover:translate-x-0.5 ${categoryClassMap[block.category]}`}
                        >
                          <div className="flex items-center justify-between gap-2">
                            <p className="truncate text-sm font-semibold">{block.title}</p>
                            <span className={`h-2.5 w-2.5 rounded-full ${categoryDotMap[block.category]}`} />
                          </div>
                          <p className="mt-1 text-xs opacity-85">
                            {block.startTime} - {block.endTime}
                          </p>
                          <p className="mt-1 text-xs opacity-80">{block.subject}</p>
                          {block.location ? <p className="mt-1 text-[11px] opacity-75">{block.location}</p> : null}
                        </div>
                      ))
                    )}
                  </div>
                </article>
              );
            })}
          </div>
        </div>

        <aside className="space-y-4 rounded-3xl border border-[var(--border)] bg-[var(--card)] p-5 shadow-sm">
          <h2 className="text-sm font-semibold uppercase tracking-[0.12em] text-[var(--text-secondary)]">Free Slot Detector</h2>
          <div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-3">
            <label className="mb-1 block text-xs font-semibold uppercase tracking-[0.1em] text-[var(--text-secondary)]">Quick Subject</label>
            <input
              value={quickSubject}
              onChange={(event) => setQuickSubject(event.target.value)}
              className="w-full rounded-lg border border-[var(--border)] bg-[var(--card)] px-3 py-2 text-sm text-[var(--text-primary)] outline-none"
              placeholder="DSA"
            />
          </div>

          <div className="space-y-2">
            {filteredSlots.length === 0 ? (
              <p className="rounded-xl border border-dashed border-[var(--border)] p-3 text-sm text-[var(--text-secondary)]">No free slots available.</p>
            ) : (
              filteredSlots.map((slot, index) => (
                <div
                  key={`${slot.dayOfWeek}-${slot.startTime}-${index}`}
                  className="rounded-xl border border-[var(--border)] bg-[var(--surface)] p-3 transition-all duration-200 hover:border-indigo-400/45"
                >
                  <p className="text-sm font-semibold text-[var(--text-primary)]">{slot.dayLabel}</p>
                  <p className="text-xs text-[var(--text-secondary)]">
                    {slot.startTime} - {slot.endTime} • {toHours(slot.durationMinutes)}
                  </p>
                  <button
                    type="button"
                    onClick={() => void handlePlanFromFreeSlot(slot)}
                    disabled={saving}
                    className="mt-2 rounded-lg border border-indigo-400/40 bg-indigo-500/10 px-2.5 py-1 text-xs font-semibold text-indigo-700 transition-colors hover:bg-indigo-500/20 disabled:opacity-60 dark:text-indigo-300"
                  >
                    Plan Study Session
                  </button>
                </div>
              ))
            )}
          </div>
        </aside>
      </div>

      {showCreateModal ? (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/35 p-4 backdrop-blur-sm" role="dialog" aria-modal="true">
          <div className="w-full max-w-xl rounded-3xl border border-white/20 bg-white/85 p-5 shadow-2xl dark:border-white/10 dark:bg-slate-950/75">
            <div className="mb-4 flex items-center justify-between">
              <h3 className="text-lg font-semibold text-[var(--text-primary)]">Create Time Block</h3>
              <button
                type="button"
                onClick={() => setShowCreateModal(false)}
                className="rounded-lg border border-[var(--border)] px-2.5 py-1 text-xs font-semibold text-[var(--text-secondary)]"
              >
                Close
              </button>
            </div>

            <form onSubmit={handleCreateBlock} className="space-y-3">
              <div className="grid gap-3 sm:grid-cols-2">
                <label className="space-y-1 text-xs font-semibold uppercase tracking-[0.1em] text-[var(--text-secondary)]">
                  Title
                  <input
                    value={form.title}
                    onChange={(event) => setForm((prev) => ({ ...prev, title: event.target.value }))}
                    className="w-full rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 py-2 text-sm text-[var(--text-primary)] outline-none"
                    required
                  />
                </label>

                <label className="space-y-1 text-xs font-semibold uppercase tracking-[0.1em] text-[var(--text-secondary)]">
                  Subject
                  <input
                    value={form.subject}
                    onChange={(event) => setForm((prev) => ({ ...prev, subject: event.target.value }))}
                    className="w-full rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 py-2 text-sm text-[var(--text-primary)] outline-none"
                  />
                </label>
              </div>

              <div className="grid gap-3 sm:grid-cols-3">
                <label className="space-y-1 text-xs font-semibold uppercase tracking-[0.1em] text-[var(--text-secondary)]">
                  Category
                  <select
                    value={form.category}
                    onChange={(event) => setForm((prev) => ({ ...prev, category: event.target.value as ScheduleCategory }))}
                    className="w-full rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 py-2 text-sm text-[var(--text-primary)] outline-none"
                  >
                    {options.categories.map((category) => (
                      <option key={category} value={category}>
                        {categoryLabel(category)}
                      </option>
                    ))}
                  </select>
                </label>

                <label className="space-y-1 text-xs font-semibold uppercase tracking-[0.1em] text-[var(--text-secondary)]">
                  Day
                  <select
                    value={form.dayOfWeek}
                    onChange={(event) => setForm((prev) => ({ ...prev, dayOfWeek: event.target.value }))}
                    className="w-full rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 py-2 text-sm text-[var(--text-primary)] outline-none"
                  >
                    {options.days.map((day) => (
                      <option key={day.value} value={day.value}>
                        {day.label}
                      </option>
                    ))}
                  </select>
                </label>

                <label className="space-y-1 text-xs font-semibold uppercase tracking-[0.1em] text-[var(--text-secondary)]">
                  Location
                  <input
                    value={form.location}
                    onChange={(event) => setForm((prev) => ({ ...prev, location: event.target.value }))}
                    className="w-full rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 py-2 text-sm text-[var(--text-primary)] outline-none"
                  />
                </label>
              </div>

              <div className="grid gap-3 sm:grid-cols-2">
                <label className="space-y-1 text-xs font-semibold uppercase tracking-[0.1em] text-[var(--text-secondary)]">
                  Start Time
                  <input
                    type="time"
                    value={form.startTime}
                    onChange={(event) => setForm((prev) => ({ ...prev, startTime: event.target.value }))}
                    className="w-full rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 py-2 text-sm text-[var(--text-primary)] outline-none"
                    required
                  />
                </label>

                <label className="space-y-1 text-xs font-semibold uppercase tracking-[0.1em] text-[var(--text-secondary)]">
                  End Time
                  <input
                    type="time"
                    value={form.endTime}
                    onChange={(event) => setForm((prev) => ({ ...prev, endTime: event.target.value }))}
                    className="w-full rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 py-2 text-sm text-[var(--text-primary)] outline-none"
                    required
                  />
                </label>
              </div>

              <div className="flex justify-end gap-2 pt-2">
                <button
                  type="button"
                  onClick={() => setShowCreateModal(false)}
                  className="rounded-xl border border-[var(--border)] px-4 py-2 text-sm font-semibold text-[var(--text-secondary)]"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={saving}
                  className="rounded-xl bg-[var(--accent)] px-4 py-2 text-sm font-semibold text-white transition-opacity disabled:opacity-65"
                >
                  {saving ? "Saving..." : "Save Block"}
                </button>
              </div>
            </form>
          </div>
        </div>
      ) : null}
    </section>
  );
}

function WidgetCard({ title, value, hint, icon }: { title: string; value: string; hint: string; icon: React.ReactNode }) {
  return (
    <article className="rounded-2xl border border-[var(--border)] bg-[var(--card)] p-4 shadow-sm transition-all duration-200 hover:-translate-y-0.5 hover:shadow">
      <div className="mb-2 inline-flex h-9 w-9 items-center justify-center rounded-xl border border-[var(--border)] bg-[var(--surface)] text-[var(--text-secondary)]">
        {icon}
      </div>
      <p className="text-xs uppercase tracking-[0.12em] text-[var(--text-secondary)]">{title}</p>
      <p className="mt-1 text-2xl font-semibold tracking-tight text-[var(--text-primary)]">{value}</p>
      <p className="text-xs text-[var(--text-secondary)]">{hint}</p>
    </article>
  );
}
